name: Makefile CI

on:
  push:
    branches: [ "root" ]
  pull_request:
    branches: [ "root" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install nasm
      run: sudo apt update && sudo apt install -y nasm 

    - name: Set up Python 3.10.8
      uses: actions/setup-python@v3
      with:
        python-version: "3.10.8"

    - name: Run tests
      run: |
        python tester.py
        make clean
